

service: dev-secret

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

plugins: 
  - serverless-offline

functions:
  create:
    handler: src/handlers/secrets.create
    events:
      - http:
          path: /secrets/
          method: post
          cors: true

  get:
    handler: src/handlers/secrets.get
    events:
      - http:
          path: /secrets/{id}
          method: get
          cors: 
            origin: '*'
            headers:
              - adminKey
          
  draw:
    handler: src/handlers/secrets.draw
    role: arn:aws:iam::117721170469:role/dev-1-naldo
    events:
      - http:
          path: /secrets/{id}/draw
          method: put
          cors: 
            origin: '*'
            headers:
              - adminKey
          
          
  createParticipant:
    handler: src/handlers/participants.create
    events:
      - http:
          path: /secrets/{id}/participants
          method: post
          cors: true
          
  deleteParticipant:
    handler: src/handlers/participants.delete
    events:
      - http:
          path: /secret/{id}/participants/{participantsId}
          method: delete
          cors:
            origin: '*'
            headers:
              - adminKey        